// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';

export interface AttachmentTypeCodeControllerFindOneRequest {
  id: number;
}

/**
 * no description
 */
export class AttachmentTypeCodeApi extends BaseAPI {
  /**
   */
  attachmentTypeCodeControllerFindAll(): Observable<void>;
  attachmentTypeCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  attachmentTypeCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    return this.request<void>(
      {
        url: '/api/attachment-type-code',
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  attachmentTypeCodeControllerFindOne({
    id,
  }: AttachmentTypeCodeControllerFindOneRequest): Observable<void>;
  attachmentTypeCodeControllerFindOne(
    { id }: AttachmentTypeCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  attachmentTypeCodeControllerFindOne(
    { id }: AttachmentTypeCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'attachmentTypeCodeControllerFindOne');

    return this.request<void>(
      {
        url: '/api/attachment-type-code/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
