// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';
import { CommentScopeCodeDto } from '../models';

export interface CommentScopeCodeControllerFindOneRequest {
  id: string;
}

/**
 * no description
 */
export class CommentScopeCodeApi extends BaseAPI {
  /**
   */
  commentScopeCodeControllerFindAll(): Observable<Array<CommentScopeCodeDto>>;
  commentScopeCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<Array<CommentScopeCodeDto>>>;
  commentScopeCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<
    Array<CommentScopeCodeDto> | RawAjaxResponse<Array<CommentScopeCodeDto>>
  > {
    return this.request<Array<CommentScopeCodeDto>>(
      {
        url: '/api/comment-scope-code',
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  commentScopeCodeControllerFindOne({
    id,
  }: CommentScopeCodeControllerFindOneRequest): Observable<CommentScopeCodeDto>;
  commentScopeCodeControllerFindOne(
    { id }: CommentScopeCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<CommentScopeCodeDto>>;
  commentScopeCodeControllerFindOne(
    { id }: CommentScopeCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<CommentScopeCodeDto | RawAjaxResponse<CommentScopeCodeDto>> {
    throwIfNullOrUndefined(id, 'id', 'commentScopeCodeControllerFindOne');

    return this.request<CommentScopeCodeDto>(
      {
        url: '/api/comment-scope-code/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
