// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  HttpHeaders,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';
import { CutBlockDto, UpdateCutBlockDto } from '../models';

export interface CutBlockControllerCreateRequest {
  cutBlockDto: CutBlockDto;
}

export interface CutBlockControllerFindOneRequest {
  id: number;
}

export interface CutBlockControllerRemoveRequest {
  id: number;
}

export interface CutBlockControllerUpdateRequest {
  id: number;
  updateCutBlockDto: UpdateCutBlockDto;
}

/**
 * no description
 */
export class CutBlockApi extends BaseAPI {
  /**
   */
  cutBlockControllerCreate({
    cutBlockDto,
  }: CutBlockControllerCreateRequest): Observable<void>;
  cutBlockControllerCreate(
    { cutBlockDto }: CutBlockControllerCreateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  cutBlockControllerCreate(
    { cutBlockDto }: CutBlockControllerCreateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(
      cutBlockDto,
      'cutBlockDto',
      'cutBlockControllerCreate'
    );

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/cut-block',
        method: 'POST',
        headers,
        body: cutBlockDto,
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  cutBlockControllerFindOne({
    id,
  }: CutBlockControllerFindOneRequest): Observable<void>;
  cutBlockControllerFindOne(
    { id }: CutBlockControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  cutBlockControllerFindOne(
    { id }: CutBlockControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'cutBlockControllerFindOne');

    return this.request<void>(
      {
        url: '/api/cut-block/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  cutBlockControllerRemove({
    id,
  }: CutBlockControllerRemoveRequest): Observable<void>;
  cutBlockControllerRemove(
    { id }: CutBlockControllerRemoveRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  cutBlockControllerRemove(
    { id }: CutBlockControllerRemoveRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'cutBlockControllerRemove');

    return this.request<void>(
      {
        url: '/api/cut-block/{id}'.replace('{id}', encodeURI(id)),
        method: 'DELETE',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  cutBlockControllerUpdate({
    id,
    updateCutBlockDto,
  }: CutBlockControllerUpdateRequest): Observable<void>;
  cutBlockControllerUpdate(
    { id, updateCutBlockDto }: CutBlockControllerUpdateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  cutBlockControllerUpdate(
    { id, updateCutBlockDto }: CutBlockControllerUpdateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'cutBlockControllerUpdate');
    throwIfNullOrUndefined(
      updateCutBlockDto,
      'updateCutBlockDto',
      'cutBlockControllerUpdate'
    );

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/cut-block/{id}'.replace('{id}', encodeURI(id)),
        method: 'PUT',
        headers,
        body: updateCutBlockDto,
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
