// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';
import { DistrictDto } from '../models';

export interface DistrictControllerFindOneRequest {
  id: number;
}

/**
 * no description
 */
export class DistrictApi extends BaseAPI {
  /**
   */
  districtControllerFindOne({
    id,
  }: DistrictControllerFindOneRequest): Observable<DistrictDto>;
  districtControllerFindOne(
    { id }: DistrictControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<DistrictDto>>;
  districtControllerFindOne(
    { id }: DistrictControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<DistrictDto | RawAjaxResponse<DistrictDto>> {
    throwIfNullOrUndefined(id, 'id', 'districtControllerFindOne');

    return this.request<DistrictDto>(
      {
        url: '/api/district'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
