// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';
import { ForestClientDto } from '../models';

export interface ForestClientControllerFindOneRequest {
  id: number;
}

/**
 * no description
 */
export class ForestClientApi extends BaseAPI {
  /**
   */
  forestClientControllerFindAll(): Observable<Array<ForestClientDto>>;
  forestClientControllerFindAll(
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<Array<ForestClientDto>>>;
  forestClientControllerFindAll(
    opts?: OperationOpts
  ): Observable<
    Array<ForestClientDto> | RawAjaxResponse<Array<ForestClientDto>>
  > {
    return this.request<Array<ForestClientDto>>(
      {
        url: '/api/forest-client',
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  forestClientControllerFindOne({
    id,
  }: ForestClientControllerFindOneRequest): Observable<ForestClientDto>;
  forestClientControllerFindOne(
    { id }: ForestClientControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<ForestClientDto>>;
  forestClientControllerFindOne(
    { id }: ForestClientControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<ForestClientDto | RawAjaxResponse<ForestClientDto>> {
    throwIfNullOrUndefined(id, 'id', 'forestClientControllerFindOne');

    return this.request<ForestClientDto>(
      {
        url: '/api/forest-client/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
