// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';
import { ResponseCodeDto } from '../models';

export interface ResponseCodeControllerFindOneRequest {
  id: string;
}

/**
 * no description
 */
export class ResponseCodeApi extends BaseAPI {
  /**
   */
  responseCodeControllerFindAll(): Observable<Array<ResponseCodeDto>>;
  responseCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<Array<ResponseCodeDto>>>;
  responseCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<
    Array<ResponseCodeDto> | RawAjaxResponse<Array<ResponseCodeDto>>
  > {
    return this.request<Array<ResponseCodeDto>>(
      {
        url: '/api/response-code',
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  responseCodeControllerFindOne({
    id,
  }: ResponseCodeControllerFindOneRequest): Observable<ResponseCodeDto>;
  responseCodeControllerFindOne(
    { id }: ResponseCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<ResponseCodeDto>>;
  responseCodeControllerFindOne(
    { id }: ResponseCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<ResponseCodeDto | RawAjaxResponse<ResponseCodeDto>> {
    throwIfNullOrUndefined(id, 'id', 'responseCodeControllerFindOne');

    return this.request<ResponseCodeDto>(
      {
        url: '/api/response-code/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
