// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';

export interface ResponseCodeControllerFindOneRequest {
  id: number;
}

/**
 * no description
 */
export class ResponseCodeApi extends BaseAPI {
  /**
   */
  responseCodeControllerFindAll(): Observable<void>;
  responseCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  responseCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    return this.request<void>(
      {
        url: '/api/response-code',
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  responseCodeControllerFindOne({
    id,
  }: ResponseCodeControllerFindOneRequest): Observable<void>;
  responseCodeControllerFindOne(
    { id }: ResponseCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  responseCodeControllerFindOne(
    { id }: ResponseCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'responseCodeControllerFindOne');

    return this.request<void>(
      {
        url: '/api/response-code/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
