// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  HttpHeaders,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';
import { RetentionAreaDto, UpdateRetentionAreaDto } from '../models';

export interface RetentionAreaControllerCreateRequest {
  retentionAreaDto: RetentionAreaDto;
}

export interface RetentionAreaControllerFindOneRequest {
  id: number;
}

export interface RetentionAreaControllerRemoveRequest {
  id: number;
}

export interface RetentionAreaControllerUpdateRequest {
  id: number;
  updateRetentionAreaDto: UpdateRetentionAreaDto;
}

/**
 * no description
 */
export class RetentionAreaApi extends BaseAPI {
  /**
   */
  retentionAreaControllerCreate({
    retentionAreaDto,
  }: RetentionAreaControllerCreateRequest): Observable<void>;
  retentionAreaControllerCreate(
    { retentionAreaDto }: RetentionAreaControllerCreateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  retentionAreaControllerCreate(
    { retentionAreaDto }: RetentionAreaControllerCreateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(
      retentionAreaDto,
      'retentionAreaDto',
      'retentionAreaControllerCreate'
    );

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/retention-area',
        method: 'POST',
        headers,
        body: retentionAreaDto,
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  retentionAreaControllerFindOne({
    id,
  }: RetentionAreaControllerFindOneRequest): Observable<void>;
  retentionAreaControllerFindOne(
    { id }: RetentionAreaControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  retentionAreaControllerFindOne(
    { id }: RetentionAreaControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'retentionAreaControllerFindOne');

    return this.request<void>(
      {
        url: '/api/retention-area/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  retentionAreaControllerRemove({
    id,
  }: RetentionAreaControllerRemoveRequest): Observable<void>;
  retentionAreaControllerRemove(
    { id }: RetentionAreaControllerRemoveRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  retentionAreaControllerRemove(
    { id }: RetentionAreaControllerRemoveRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'retentionAreaControllerRemove');

    return this.request<void>(
      {
        url: '/api/retention-area/{id}'.replace('{id}', encodeURI(id)),
        method: 'DELETE',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  retentionAreaControllerUpdate({
    id,
    updateRetentionAreaDto,
  }: RetentionAreaControllerUpdateRequest): Observable<void>;
  retentionAreaControllerUpdate(
    { id, updateRetentionAreaDto }: RetentionAreaControllerUpdateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  retentionAreaControllerUpdate(
    { id, updateRetentionAreaDto }: RetentionAreaControllerUpdateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'retentionAreaControllerUpdate');
    throwIfNullOrUndefined(
      updateRetentionAreaDto,
      'updateRetentionAreaDto',
      'retentionAreaControllerUpdate'
    );

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/retention-area/{id}'.replace('{id}', encodeURI(id)),
        method: 'PUT',
        headers,
        body: updateRetentionAreaDto,
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
