// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';

export interface SubmissionTypeCodeControllerFindOneRequest {
  id: number;
}

/**
 * no description
 */
export class SubmissionTypeCodeApi extends BaseAPI {
  /**
   */
  submissionTypeCodeControllerFindAll(): Observable<void>;
  submissionTypeCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  submissionTypeCodeControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    return this.request<void>(
      {
        url: '/api/submission-type-code',
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  submissionTypeCodeControllerFindOne({
    id,
  }: SubmissionTypeCodeControllerFindOneRequest): Observable<void>;
  submissionTypeCodeControllerFindOne(
    { id }: SubmissionTypeCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  submissionTypeCodeControllerFindOne(
    { id }: SubmissionTypeCodeControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'submissionTypeCodeControllerFindOne');

    return this.request<void>(
      {
        url: '/api/submission-type-code/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
