// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreateInteractionDto
 */
export interface CreateInteractionDto {
  /**
   * @type {number}
   * @memberof CreateInteractionDto
   */
  id: number;
  /**
   * @type {number}
   * @memberof CreateInteractionDto
   */
  revisionCount: number;
  /**
   * @type {string}
   * @memberof CreateInteractionDto
   */
  createTimestamp: string;
  /**
   * @type {string}
   * @memberof CreateInteractionDto
   */
  createUser: string;
  /**
   * @type {string}
   * @memberof CreateInteractionDto
   */
  updateTimestamp: string;
  /**
   * @type {string}
   * @memberof CreateInteractionDto
   */
  updateUser: string;
  /**
   * @type {string}
   * @memberof CreateInteractionDto
   */
  stakeholder: string;
  /**
   * @type {string}
   * @memberof CreateInteractionDto
   */
  communicationDate: string;
  /**
   * @type {string}
   * @memberof CreateInteractionDto
   */
  communicationDetails: string;
  /**
   * @type {number}
   * @memberof CreateInteractionDto
   */
  projectId: number;
  /**
   * @type {number}
   * @memberof CreateInteractionDto
   */
  attachmentId: number;
}
