// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreatePublicCommentDto
 */
export interface CreatePublicCommentDto {
  /**
   * @type {number}
   * @memberof CreatePublicCommentDto
   */
  id: number;
  /**
   * @type {number}
   * @memberof CreatePublicCommentDto
   */
  revisionCount: number;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  createTimestamp: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  createUser: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  updateTimestamp: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  updateUser: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  feedback: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  name: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  location: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  email: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  phoneNumber: string;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  responseDetails: string;
  /**
   * @type {number}
   * @memberof CreatePublicCommentDto
   */
  projectId: number;
  /**
   * @type {object}
   * @memberof CreatePublicCommentDto
   */
  project: object;
  /**
   * @type {string}
   * @memberof CreatePublicCommentDto
   */
  responseCode: string;
  /**
   * @type {object}
   * @memberof CreatePublicCommentDto
   */
  response: object;
}
