// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateSubmissionDto
 */
export interface UpdateSubmissionDto {
  /**
   * @type {number}
   * @memberof UpdateSubmissionDto
   */
  revisionCount: number;
  /**
   * @type {string}
   * @memberof UpdateSubmissionDto
   */
  createTimestamp: string;
  /**
   * @type {string}
   * @memberof UpdateSubmissionDto
   */
  createUser: string;
  /**
   * @type {string}
   * @memberof UpdateSubmissionDto
   */
  updateTimestamp: string;
  /**
   * @type {string}
   * @memberof UpdateSubmissionDto
   */
  updateUser: string;
  /**
   * @type {object}
   * @memberof UpdateSubmissionDto
   */
  geometry: object;
  /**
   * @type {number}
   * @memberof UpdateSubmissionDto
   */
  projectId: number;
  /**
   * @type {object}
   * @memberof UpdateSubmissionDto
   */
  project: object;
  /**
   * @type {string}
   * @memberof UpdateSubmissionDto
   */
  submissionTypeCode: string;
  /**
   * @type {object}
   * @memberof UpdateSubmissionDto
   */
  submissionType: object;
}
