/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SpatialObjectCodeEnum = 'CUT_BLOCK' | 'ROAD_SECTION' | 'WTRA';

export const SpatialObjectCodeEnum = {
    CutBlock: 'CUT_BLOCK' as SpatialObjectCodeEnum,
    RoadSection: 'ROAD_SECTION' as SpatialObjectCodeEnum,
    Wtra: 'WTRA' as SpatialObjectCodeEnum
};

