// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  HttpHeaders,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';
import { CreateProjectDto, UpdateProjectDto } from '../models';

export interface ProjectControllerCreateRequest {
  createProjectDto: CreateProjectDto;
}

export interface ProjectControllerFindOneRequest {
  id: number;
}

export interface ProjectControllerRemoveRequest {
  id: number;
}

export interface ProjectControllerUpdateRequest {
  id: number;
  updateProjectDto: UpdateProjectDto;
}

/**
 * no description
 */
export class ProjectApi extends BaseAPI {
  /**
   */
  projectControllerCreate({
    createProjectDto,
  }: ProjectControllerCreateRequest): Observable<void>;
  projectControllerCreate(
    { createProjectDto }: ProjectControllerCreateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  projectControllerCreate(
    { createProjectDto }: ProjectControllerCreateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(
      createProjectDto,
      'createProjectDto',
      'projectControllerCreate'
    );

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/project',
        method: 'POST',
        headers,
        body: createProjectDto,
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  projectControllerFindOne({
    id,
  }: ProjectControllerFindOneRequest): Observable<void>;
  projectControllerFindOne(
    { id }: ProjectControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  projectControllerFindOne(
    { id }: ProjectControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'projectControllerFindOne');

    return this.request<void>(
      {
        url: '/api/project/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  projectControllerRemove({
    id,
  }: ProjectControllerRemoveRequest): Observable<void>;
  projectControllerRemove(
    { id }: ProjectControllerRemoveRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  projectControllerRemove(
    { id }: ProjectControllerRemoveRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'projectControllerRemove');

    return this.request<void>(
      {
        url: '/api/project/{id}'.replace('{id}', encodeURI(id)),
        method: 'DELETE',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  projectControllerUpdate({
    id,
    updateProjectDto,
  }: ProjectControllerUpdateRequest): Observable<void>;
  projectControllerUpdate(
    { id, updateProjectDto }: ProjectControllerUpdateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  projectControllerUpdate(
    { id, updateProjectDto }: ProjectControllerUpdateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'projectControllerUpdate');
    throwIfNullOrUndefined(
      updateProjectDto,
      'updateProjectDto',
      'projectControllerUpdate'
    );

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/project/{id}'.replace('{id}', encodeURI(id)),
        method: 'PUT',
        headers,
        body: updateProjectDto,
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
