// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';

export interface ProjectsControllerFindByFspIdRequest {
  id: number;
}

/**
 * no description
 */
export class ProjectsApi extends BaseAPI {
  /**
   */
  projectsControllerFindAll(): Observable<void>;
  projectsControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  projectsControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    return this.request<void>(
      {
        url: '/api/projects',
        method: 'POST',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  projectsControllerFindByFspId({
    id,
  }: ProjectsControllerFindByFspIdRequest): Observable<void>;
  projectsControllerFindByFspId(
    { id }: ProjectsControllerFindByFspIdRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  projectsControllerFindByFspId(
    { id }: ProjectsControllerFindByFspIdRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'projectsControllerFindByFspId');

    return this.request<void>(
      {
        url: '/api/projects/byFspId/{id}'.replace('{id}', encodeURI(id)),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
