// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import {
  BaseAPI,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime';

export interface PublicCommentsControllerFindByProjectIdRequest {
  id: number;
}

/**
 * no description
 */
export class PublicCommentsApi extends BaseAPI {
  /**
   */
  publicCommentsControllerFindAll(): Observable<void>;
  publicCommentsControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  publicCommentsControllerFindAll(
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    return this.request<void>(
      {
        url: '/api/public-comments',
        method: 'POST',
      },
      opts ? opts.responseOpts : undefined
    );
  }

  /**
   */
  publicCommentsControllerFindByProjectId({
    id,
  }: PublicCommentsControllerFindByProjectIdRequest): Observable<void>;
  publicCommentsControllerFindByProjectId(
    { id }: PublicCommentsControllerFindByProjectIdRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  publicCommentsControllerFindByProjectId(
    { id }: PublicCommentsControllerFindByProjectIdRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'publicCommentsControllerFindByProjectId');

    return this.request<void>(
      {
        url: '/api/public-comments/byProjectId/{id}'.replace(
          '{id}',
          encodeURI(id)
        ),
        method: 'GET',
      },
      opts ? opts.responseOpts : undefined
    );
  }
}
