/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AttachmentTypeEnum = 'PUBLIC_NOTICE' | 'INTERACTION' | 'SUPPORTING_DOC';

export const AttachmentTypeEnum = {
    PublicNotice: 'PUBLIC_NOTICE' as AttachmentTypeEnum,
    Interaction: 'INTERACTION' as AttachmentTypeEnum,
    SupportingDoc: 'SUPPORTING_DOC' as AttachmentTypeEnum
};

