/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AwsCognitoOauthConfig } from './awsCognitoOauthConfig';


export interface AwsCognitoConfig { 
    enabled: boolean;
    aws_cognito_domain: string;
    aws_cognito_region: string;
    aws_user_pools_id: string;
    aws_user_pools_web_client_id: string;
    aws_mandatory_sign_in: string;
    oauth: AwsCognitoOauthConfig;
    federationTarget: string;
}

