/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InteractionResponse { 
    projectId: number;
    stakeholder?: string;
    communicationDate?: string;
    communicationDetails: string;
    attachmentId?: number;
    id: number;
    revisionCount: number;
    /**
     * ISO-formatted timestamp
     */
    createTimestamp: string;
}

