/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectSpatialDetail { 
    object_id: number;
    source_table: string;
    name: string;
    geometry: object;
    planned_development_date: string;
    planned_area_ha: number;
    planned_length_km: number;
    submission_type_code: string;
    submission_type: object;
    project_id: number;
}

