/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ForestClientResponse } from './forestClientResponse';
import { WorkflowStateCode } from './workflowStateCode';
import { DistrictResponse } from './districtResponse';


export interface ProjectResponse { 
    id: number;
    name: string;
    description: string;
    /**
     * ISO-formatted date
     */
    commentingOpenDate: string;
    /**
     * ISO-formatted date
     */
    commentingClosedDate: string;
    fspId: number;
    district: DistrictResponse;
    forestClient: ForestClientResponse;
    workflowState: WorkflowStateCode;
    revisionCount: number;
    /**
     * ISO-formatted timestamp
     */
    createTimestamp: string;
}

