/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectSpatialDetail { 
    objectId: number;
    sourceTable: string;
    name: string;
    geometry: object;
    plannedDevelopmentDate: string;
    plannedAreaHa: number;
    plannedLengthKm: number;
    submissionTypeCode: string;
    submissionType: object;
    projectId: number;
}

