/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProjectPlanCodeEnum = 'FSP' | 'WOODLOT';

export const ProjectPlanCodeEnum = {
    Fsp: 'FSP' as ProjectPlanCodeEnum,
    Woodlot: 'WOODLOT' as ProjectPlanCodeEnum
};

