/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectCreateRequest { 
    name: string;
    description: string;
    /**
     * ISO-formatted date
     */
    commentingOpenDate: string;
    /**
     * ISO-formatted date
     */
    commentingClosedDate: string;
    forestClientNumber: string;
    fspId: number;
    districtId: number;
}

