/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicNoticeCreateRequest { 
    projectId: number;
    reviewAddress: string;
    reviewBusinessHours: string;
    receiveCommentsAddress: string;
    receiveCommentsBusinessHours: string;
    isReceiveCommentsSameAsReview: boolean;
    mailingAddress: string;
    email: string;
    operationStartYear: number;
    operationEndYear: number;
    /**
     * Date planed for online public notice posted.
     */
    postDate: string;
}

