/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseCode } from './responseCode';
import { CommentScopeCode } from './commentScopeCode';


export interface PublicCommentAdminResponse { 
    projectId: number;
    scopeCutBlockId: number;
    scopeRoadSectionId: number;
    feedback: string;
    name: string;
    location: string;
    email: string;
    phoneNumber: string;
    id: number;
    revisionCount: number;
    /**
     * ISO-formatted timestamp
     */
    createTimestamp: string;
    commentScope: CommentScopeCode;
    response: ResponseCode;
    responseDetails: string;
}

