/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ResponseCodeEnum = 'IRRELEVANT' | 'CONSIDERED' | 'ADDRESSED';

export const ResponseCodeEnum = {
    Irrelevant: 'IRRELEVANT' as ResponseCodeEnum,
    Considered: 'CONSIDERED' as ResponseCodeEnum,
    Addressed: 'ADDRESSED' as ResponseCodeEnum
};

