/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpatialFeatureBcgwResponse { 
    fomId: number;
    featureType: SpatialFeatureBcgwResponse.FeatureTypeEnum;
    featureId: number;
    /**
     * Maximum length is expected to be < 100
     */
    fspHolderName: string;
    lifecycleStatus: SpatialFeatureBcgwResponse.LifecycleStatusEnum;
    /**
     * Format: YYYY-MM-DD
     */
    createDate: string;
    /**
     * Format: GeoJSON Geometry as per RFC 7946 https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.
     */
    geometry: object;
    /**
     * Format: YYYY-MM-DD
     */
    plannedDevelopmentDate: string;
    plannedAreaHa: number;
    plannedLengthKm: number;
}
export namespace SpatialFeatureBcgwResponse {
    export type FeatureTypeEnum = 'cut_block' | 'road_section' | 'retention_area';
    export const FeatureTypeEnum = {
        CutBlock: 'cut_block' as FeatureTypeEnum,
        RoadSection: 'road_section' as FeatureTypeEnum,
        RetentionArea: 'retention_area' as FeatureTypeEnum
    };
    export type LifecycleStatusEnum = 'Proposed' | 'Final';
    export const LifecycleStatusEnum = {
        Proposed: 'Proposed' as LifecycleStatusEnum,
        Final: 'Final' as LifecycleStatusEnum
    };
}


