/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmissionTypeCode } from './submissionTypeCode';
import { FeatureTypeCode } from './featureTypeCode';


export interface SpatialFeaturePublicResponse { 
    featureType: FeatureTypeCode;
    featureId: number;
    name: string;
    /**
     * Format: GeoJSON Geometry object
     */
    geometry: object;
    /**
     * Format: YYYY-MM-DD
     */
    plannedDevelopmentDate: string;
    plannedAreaHa: number;
    plannedLengthKm: number;
    submissionType: SubmissionTypeCode;
}

