/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SubmissionTypeCodeEnum = 'PROPOSED' | 'FINAL';

export const SubmissionTypeCodeEnum = {
    Proposed: 'PROPOSED' as SubmissionTypeCodeEnum,
    Final: 'FINAL' as SubmissionTypeCodeEnum
};

