/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmissionTypeCodeEnum } from './submissionTypeCodeEnum';


export interface SubmissionMetricsResponse { 
    projectId: number;
    submissionId: number;
    submissionTypeCode: SubmissionTypeCodeEnum;
    cutblocks: Array<SubmissionMetricsResponse>;
    roadSections: Array<SubmissionMetricsResponse>;
    retentionAreas: Array<SubmissionMetricsResponse>;
}

