/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WorkflowStateEnum = 'INITIAL' | 'PUBLISHED' | 'COMMENT_OPEN' | 'COMMENT_CLOSED' | 'FINALIZED' | 'EXPIRED';

export const WorkflowStateEnum = {
    Initial: 'INITIAL' as WorkflowStateEnum,
    Published: 'PUBLISHED' as WorkflowStateEnum,
    CommentOpen: 'COMMENT_OPEN' as WorkflowStateEnum,
    CommentClosed: 'COMMENT_CLOSED' as WorkflowStateEnum,
    Finalized: 'FINALIZED' as WorkflowStateEnum,
    Expired: 'EXPIRED' as WorkflowStateEnum
};

