// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DistrictDto
 */
export interface DistrictDto {
  /**
   * @type {number}
   * @memberof DistrictDto
   */
  id: number;
  /**
   * @type {number}
   * @memberof DistrictDto
   */
  revisionCount: number;
  /**
   * @type {string}
   * @memberof DistrictDto
   */
  createTimestamp: string;
  /**
   * @type {string}
   * @memberof DistrictDto
   */
  createUser: string;
  /**
   * @type {string}
   * @memberof DistrictDto
   */
  updateTimestamp: string;
  /**
   * @type {string}
   * @memberof DistrictDto
   */
  updateUser: string;
  /**
   * @type {string}
   * @memberof DistrictDto
   */
  name: string;
}
