// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PublicCommentDto
 */
export interface PublicCommentDto {
  /**
   * @type {number}
   * @memberof PublicCommentDto
   */
  id: number;
  /**
   * @type {number}
   * @memberof PublicCommentDto
   */
  revisionCount: number;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  createTimestamp: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  createUser: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  updateTimestamp: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  updateUser: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  feedback: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  name: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  location: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  email: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  phoneNumber: string;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  responseDetails: string;
  /**
   * @type {number}
   * @memberof PublicCommentDto
   */
  projectId: number;
  /**
   * @type {object}
   * @memberof PublicCommentDto
   */
  project: object;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  responseCode: string;
  /**
   * @type {object}
   * @memberof PublicCommentDto
   */
  response: object;
  /**
   * @type {string}
   * @memberof PublicCommentDto
   */
  commentScopeCode: string;
  /**
   * @type {object}
   * @memberof PublicCommentDto
   */
  commentScope: object;
  /**
   * @type {number}
   * @memberof PublicCommentDto
   */
  scopeCutBlockId: number;
  /**
   * @type {number}
   * @memberof PublicCommentDto
   */
  scopeRoadSectionId: number;
}
