// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RoadSectionDto
 */
export interface RoadSectionDto {
  /**
   * @type {number}
   * @memberof RoadSectionDto
   */
  id: number;
  /**
   * @type {number}
   * @memberof RoadSectionDto
   */
  revisionCount: number;
  /**
   * @type {string}
   * @memberof RoadSectionDto
   */
  createTimestamp: string;
  /**
   * @type {string}
   * @memberof RoadSectionDto
   */
  createUser: string;
  /**
   * @type {string}
   * @memberof RoadSectionDto
   */
  updateTimestamp: string;
  /**
   * @type {string}
   * @memberof RoadSectionDto
   */
  updateUser: string;
  /**
   * @type {object}
   * @memberof RoadSectionDto
   */
  geometry: object;
  /**
   * @type {string}
   * @memberof RoadSectionDto
   */
  plannedDevelopmentDate: string;
  /**
   * @type {number}
   * @memberof RoadSectionDto
   */
  plannedLengthKm: number;
  /**
   * @type {number}
   * @memberof RoadSectionDto
   */
  submissionId: number;
}
