// tslint:disable
/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SubmissionTypeCodeDto
 */
export interface SubmissionTypeCodeDto {
  /**
   * @type {string}
   * @memberof SubmissionTypeCodeDto
   */
  code: string;
  /**
   * @type {string}
   * @memberof SubmissionTypeCodeDto
   */
  description: string;
}
