apiVersion: v1
kind: Template
metadata:
  name: mirror-build
labels:
  template: mirror-build
#  app: ${NAME}${SUFFIX}
#  app.kubernetes.io/component: database
#  app.kubernetes.io/name: patroni
#  app.kubernetes.io/managed-by: template
#  app.kubernetes.io/version: "${PG_VERSION}"
parameters:
#  - name: NAME
#    value: patroni
#  - name: SUFFIX
#  - name: OUT_VERSION
#    description: Ouput version
#    value: "v10-latest"
#  - name: GIT_URI
#    value: https://github.com/BCDevOps/platform-services.git
#  - name: GIT_REF
#    value: master
  - name: DOCKER_IMAGE_NAME
    required: true
  - name: OCP_IMAGE_NAME
    required: true
  - name: IMAGE_VERSION
    required: true
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: ${OCP_IMAGE_NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    name: ${OCP_IMAGE_NAME}:${IMAGE_VERSION}
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: registry.hub.docker.com/library/${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}
    importPolicy:
      scheduled: true
    name: "${IMAGE_VERSION}"
    referencePolicy:
      type: Local