export * from './attachment.service';
import { AttachmentService } from './attachment.service';
export * from './attachmentTypeCode.service';
import { AttachmentTypeCodeService } from './attachmentTypeCode.service';
export * from './attachments.service';
import { AttachmentsService } from './attachments.service';
export * from './commentScopeCode.service';
import { CommentScopeCodeService } from './commentScopeCode.service';
export * from './cutBlock.service';
import { CutBlockService } from './cutBlock.service';
export * from './cutBlocks.service';
import { CutBlocksService } from './cutBlocks.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './district.service';
import { DistrictService } from './district.service';
export * from './forestClient.service';
import { ForestClientService } from './forestClient.service';
export * from './forestStewardshipPlan.service';
import { ForestStewardshipPlanService } from './forestStewardshipPlan.service';
export * from './forestStewardshipPlans.service';
import { ForestStewardshipPlansService } from './forestStewardshipPlans.service';
export * from './fspDistrictXref.service';
import { FspDistrictXrefService } from './fspDistrictXref.service';
export * from './fspDistrictXrefs.service';
import { FspDistrictXrefsService } from './fspDistrictXrefs.service';
export * from './interaction.service';
import { InteractionService } from './interaction.service';
export * from './interactions.service';
import { InteractionsService } from './interactions.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './projects.service';
import { ProjectsService } from './projects.service';
export * from './publicComment.service';
import { PublicCommentService } from './publicComment.service';
export * from './publicComments.service';
import { PublicCommentsService } from './publicComments.service';
export * from './responseCode.service';
import { ResponseCodeService } from './responseCode.service';
export * from './retentionArea.service';
import { RetentionAreaService } from './retentionArea.service';
export * from './retentionAreas.service';
import { RetentionAreasService } from './retentionAreas.service';
export * from './roadSection.service';
import { RoadSectionService } from './roadSection.service';
export * from './roadSections.service';
import { RoadSectionsService } from './roadSections.service';
export * from './submission.service';
import { SubmissionService } from './submission.service';
export * from './submissionTypeCode.service';
import { SubmissionTypeCodeService } from './submissionTypeCode.service';
export * from './submissions.service';
import { SubmissionsService } from './submissions.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './workflowStateCode.service';
import { WorkflowStateCodeService } from './workflowStateCode.service';
export const APIS = [AttachmentService, AttachmentTypeCodeService, AttachmentsService, CommentScopeCodeService, CutBlockService, CutBlocksService, DefaultService, DistrictService, ForestClientService, ForestStewardshipPlanService, ForestStewardshipPlansService, FspDistrictXrefService, FspDistrictXrefsService, InteractionService, InteractionsService, ProjectService, ProjectsService, PublicCommentService, PublicCommentsService, ResponseCodeService, RetentionAreaService, RetentionAreasService, RoadSectionService, RoadSectionsService, SubmissionService, SubmissionTypeCodeService, SubmissionsService, UserService, WorkflowStateCodeService];
