export * from './attachment.service';
import { AttachmentService } from './attachment.service';
export * from './attachmentTypeCode.service';
import { AttachmentTypeCodeService } from './attachmentTypeCode.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './commentScopeCode.service';
import { CommentScopeCodeService } from './commentScopeCode.service';
export * from './district.service';
import { DistrictService } from './district.service';
export * from './forestClient.service';
import { ForestClientService } from './forestClient.service';
export * from './interaction.service';
import { InteractionService } from './interaction.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './publicComment.service';
import { PublicCommentService } from './publicComment.service';
export * from './responseCode.service';
import { ResponseCodeService } from './responseCode.service';
export * from './submission.service';
import { SubmissionService } from './submission.service';
export * from './submissionTypeCode.service';
import { SubmissionTypeCodeService } from './submissionTypeCode.service';
export * from './workflowStateCode.service';
import { WorkflowStateCodeService } from './workflowStateCode.service';
export const APIS = [AttachmentService, AttachmentTypeCodeService, AuthService, CommentScopeCodeService, DistrictService, ForestClientService, InteractionService, ProjectService, PublicCommentService, ResponseCodeService, SubmissionService, SubmissionTypeCodeService, WorkflowStateCodeService];
