FROM artifacts.developer.gov.bc.ca/docker-remote/postgis/postgis:13-3.1
# Use a specific version to avoid the risk of even minor/patch upgrades not working automatically due to required manual upgrade steps
# Cannot use alpine version because only debian supports running as any user under openshift as per https://registry.hub.docker.com/_/postgres/
