
# Cannot use alpine version because only debian supports running as any user under openshift as per https://registry.hub.docker.com/_/postgres/
#FROM image-registry.openshift-image-registry.svc:5000/a4b31c-tools/postgis:13-3.1
FROM postgis:13-3.1

